files:
  - source: /application/locale/messages.pot
    translation: /application/locale/%two_letters_code%_%locale%/LC_MESSAGES/messages.po
    languages_mapping:
      two_letters_code:
        de: de
        es: es
        it: it
        fr: fr
      locale:
        de: DE
        es: ES
        it: IT
        fr: FR
preserve_hierarchy: 1
