files:
  - source: '/application/locale/messages.pot'
    translation: '/application/locale/%locale_with_underscore%/LC_MESSAGES/messages.po'
    skip_untranslated_files: true
    skip_untranslated_strings: true

    languages_mapping:
      locale_with_underscore:
        de: de_DE
        es: es_ES
        it: it_IT
        fr: fr_FR

"preserve_hierarchy": true
