name: Compile .mo files from changed .po files

on: 
  push:
    paths:
      - '**/*.po'
    branches:
      - 'gettext_po_test'

jobs:
  compile_mo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: HB9HIL/wavelog
        ref: gettext_po_test
        fetch-depth: 2

    - name: Set up gettext
      run: sudo apt-get install -y gettext

    - name: Compile .mo files from changed .po files
      run: |
        for po in $(git diff --name-only HEAD~1 HEAD | grep '\.po$'); do
          mo="${po%.po}.mo";
          msgfmt --verbose -o "$mo" "$po";
        done

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add .
        git commit -m "Compiled .mo file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
