name: Cypress Tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - cypress

jobs:
  cypress-e2e-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cypress
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-

      - name: Install dependencies
        run: npm install

      - name: Build Docker services
        run: sudo docker compose -f cypress_testserver.yml up -d

      - name: Wait for services to start
        run: sleep 5

      - name: Run Cypress tests
        run: npx cypress run
      
      - name: Shutdown the container
        run: sudo docker compose -f cypress_testserver.yml down

      - name: Remove the docker volumes
        run: sudo docker volume rm wavelog-web-1 && sudo docker volume rm wavelog-db

