name: Cypress Tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - cypress

jobs:
  cypress-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Cypress
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-

      - name: Install Cypress
        run: npm install cypress

      - name: Build Docker services
        run: docker-compose up -d

      - name: Wait for services to start
        run: sleep 5

      - name: Run Cypress tests
        run: npx cypress run
