name: Translation Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: HB9HIL/wavelog
        ref: gettext_po_test

    - name: Set up gettext
      run: sudo apt-get install -y gettext

    - name: Create POT file
      run: xgettext -o application/locale/messages.pot --from-code=UTF-8 -k__ -L PHP $(find . -name "*.php")

    - name: Merge POT into PO files
      run: |
        for po in $(find . -name "*.po"); do
          msgmerge -U "$po" application/locale/messages.pot;
        done

    - name: Compile MO files from PO files
      run: |
        for po in $(find . -name "*.po"); do
          mo="${po%.po}.mo";
          msgfmt -o "$mo" "$po";
        done

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add .
        git commit -m "Update translations"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
